/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.amulittle.libbluefoxgame;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        
    }
}
