/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.amulittle.libbluefoxgame;

public interface IPlugin {
    public String Name = "Default";
    public String[] Description = new String[] {"Default"};
}
